version: "3.9"

services:
  minio:
    image: minio/minio:RELEASE.2023-06-29T05-12-28Z
    container_name: minio
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    command:
      server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
  mc:
    image: minio/mc:RELEASE.2023-06-28T21-54-17Z
    container_name: mc
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    entrypoint: >
      /bin/sh -c "
      mc alias set myminio http://minio:9000 root password;
      mc mb myminio/files;
      mc cp init_data/* myminio/files;
      "
    volumes:
      - ./init_data:/init_data
